### ISSUE TITLE
Passwordless Auth with MVC Client

### ISSUE THREAD

**Issue by prabhakarreddy1234** [Jurabek/IdentityServer4.PhoneNumberAuth#1]
I see that you Sample Client project is empty. Did you manage to have MVC client with this PasswordLess auth Idp ?

**Comment by jurabek** [comment]
all endpoints are ready, it is Web API controllers of course you can use your mvc client too, and has example on readme

**Comment by prabhakarreddy1234** [comment]
Thanks Jurabek,  Is there any Middleware for MVC client which i could use with your passwordless host. I just want to have mechanism for storing cookie and [Authorize] ability.

**Comment by jurabek** [comment]
unfortunately, this is not cookie-based auth, it is JWT token based auth, it implemented top of the IdentityServer4 Middleware, I would say the extension for IdentityServer4

**Comment by jurabek** [comment]
I would recommend you to look identity server samples https://github.com/IdentityServer/IdentityServer4.Samples
