### ISSUE TITLE
How do we refresh token?

### ISSUE THREAD

**Issue by pinkal23785** [Jurabek/IdentityServer4.PhoneNumberAuth#12]

**Comment by jurabek** [comment]
@pinkal23785 

In the response you will get `refresh_token` as well just reuse it to get a new token, you can find more detailed info [here](https://identityserver4.readthedocs.io/en/latest/topics/refresh_tokens.html)
```
POST /connect/token

    client_id=client&
    client_secret=secret&
    grant_type=refresh_token&
    refresh_token=hdh922
```

Getting `refresh_token`enabled [here](https://github.com/Jurabek/IdentityServer4.PhoneNumberAuth/blob/76d1710af6456ad2f5cd84a221b5b3d460ef7fbf/IdentityServer4.PhoneNumberAuth/Configuration/Config.cs#L43) by setting `AllowOfflineAccess = true`

**Comment by jurabek** [comment]
closing issue, please feel free to reopen it if you have further questions.
