### ISSUE TITLE
why is the put method there?

### ISSUE THREAD

**Issue by paulvanbladel** [Jurabek/IdentityServer4.PhoneNumberAuth#2]
Very interesting project. Thanks for sharing.
I hope you don't mind I ask a question here?

I saw there is also a put method with param resend_token.
What's the idea behind this?
thanks
paul.

**Comment by jurabek** [comment]
resend_token in order to resend sms in case user not recieves code, you can use PUT method with resend_token for example every 60 seconds

**Comment by paulvanbladel** [comment]
@Jurabek cool. thanks.
Would you recommend a similar flow for an email based passwordless system or is this fundamentally different?

**Comment by jurabek** [comment]
it is almost same, you need just use email service instead sms service

**Comment by paulvanbladel** [comment]
@Jurabek I'm trying to get my head around the usage of oidc-client.js in combination with passwordless. 
Do you recommend calling the connect/token endpoint (which triggers your grant validator in IdS) directly from a javascript client? The point is that there is an api secret involved.

**Comment by jurabek** [comment]
@paulvanbladel you can use connect/token endpoint from oidc-client or custom http call however, you can make Public Client without using api secret.
