### ISSUE TITLE
Renew JWT?

### ISSUE THREAD

**Issue by Abdulrhman5** [Jurabek/IdentityServer4.PhoneNumberAuth#4]
Awesome work, Thank you.

If you could illustrate how to renew the JWT from refresh token.

**Comment by jurabek** [comment]
@Abduolrhman you can read more about http://docs.identityserver.io/en/latest/endpoints/token.html

to solve this issue you need just change `grant_type=refresh_token` for example 
```curl -H "Content-Type: application/x-www-form-urlencoded" \
     -X POST \ 
     -d grant_type=refresh_token&refresh_token=CfDJ8F2fHxOfr9xAtcydsuwqSAS.... \ 
      http://localhost:62537/connect/token
```
