### ISSUE TITLE
Potential security issue: TOTP with SHA(PhoneNumber)

### ISSUE THREAD

**Issue by thomasgalliker** [Jurabek/IdentityServer4.PhoneNumberAuth#5]
Question concering security in VerifyPhoneNumberController: Don't you think it's unsecure if you use the hash of PhoneNumber as SecurityStamp? An attacker could potentially generate its own TOTP tokens? I'm not sure but I guess SecurityStamp is pretty much the only secret part in this TOTP generation... SHA(PhoneNumber) is not secure in my eyes because it's reproductible on the client side.

**Comment by jurabek** [comment]
@thomasgalliker why not use more secure way `SecurityStamp = your_secret_key + loginViewModel.PhoneNumber.Sha256()` with certificate

**Comment by thomasgalliker** [comment]
Yes, something like this could work. My assumption is that SecurityStamp needs to be secret as it is used for token generation in many scenarios. The relevant code in your repo is - unfortunately - already distributed in several other repos.

I consider a solution where I generate a random number as SecurityStamp and store it in a database. Theoretically, you could also store it in a memory cache on the server, but this would impact scalability.

**Comment by jurabek** [comment]
lets keep it open until fixed
