### ISSUE TITLE
Native Mobile Client Suitability

### ISSUE THREAD

**Issue by garethkelly-dev** [Jurabek/IdentityServer4.PhoneNumberAuth#7]
This is a great project and exactly what I was looking for, I am trying to replicate the Tinder authentication process which is OTP via SMS.

I'm slightly confused around the implementation for native mobile. Reading the best practices client_secret should not be added to mobile apps as they can be accessed when decompiling source code.
I can set RequireClientSecret = false which will mean client secret does not have to be sent. Would this make the phonenumber grant type still secure?

[Best practice](https://www.identityserver.com/articles/fact-sheet-the-dangers-of-using-the-password-grant-type-with-mobile-applications) seems to steer away from password grant on mobile (which I think PhoneNumberAuth is a version of?)
I see most of the risks migrated by:

- Short lived user passcodes
- Enabled account lockout for x failed attempts and request reset passcode so limits brute force

Wondering do you have an opinion on if this project is suitable for native mobile apps or is there any further config?

**Comment by jurabek** [comment]
Hi @GazKel, this project is basically a custom `grant_type` implementation of Authorization/Authentication with SMS which is the same as the `client_credentials` grant_type it is a bit complex modification.

as you realize `client_credentials` is not recommended for Native/Mobile or SPA applications. For mobile apps recommended way is obviously the Implicit flow type, which is not POST request, you should use Browser on your mobile.

The diagram below shows how it can be done, 
![image](https://user-images.githubusercontent.com/8397056/93597313-2305ba80-f9bb-11ea-8022-6781b783588c.png)

For achieving for your goal in this flow type:
you should have to reimplement step 5: 
- You gonna prompt to the user  web page with `Phone Number field`
- When the user sends the number you will validate it and send the OTP via SMS, which is the same as this [controller](https://github.com/Jurabek/IdentityServer4.PhoneNumberAuth/blob/master/IdentityServer4.PhoneNumberAuth/Controllers/VerifyPhoneNumberController.cs)
- Then you gonna show another page when the user should have to enter the OTP code from the SMS
- When the user presses the button, in your action should do the same logic as [here](https://github.com/Jurabek/IdentityServer4.PhoneNumberAuth/blob/master/IdentityServer4.PhoneNumberAuth/Validation/PhoneNumberTokenGrantValidator.cs)

I guess this is more simple then custom `grant_type`. 
FYI: you can implement it all things mentioned above from this [sample apps method](https://github.com/IdentityServer/IdentityServer4/blob/cb5d7c9a868b067ccbe1db874fe67f51d1bb1e94/samples/Quickstarts/6_AspNetIdentity/src/IdentityServerAspNetIdentity/Quickstart/Account/AccountController.cs#L73)

**Comment by jurabek** [comment]
closing this issue, if you have any questions feel free to reopen it
