### ISSUE TITLE
AddAspNetIdentity doesn not exist in AddIdentityServer

### ISSUE THREAD

**Issue by farshidtorkaman** [Jurabek/IdentityServer4.PhoneNumberAuth#8]
hi. i am using .net core 3.1 and IdentityServer 4.1.1 .
in startup configuration I can not use `AddAspNetIdentity<ApplicationUser>` .
what should I do for that?
because when I want to sign in with `_signInManager.SignInAsync(user, true);` i got an error 'sub claim is missing'

**Comment by jurabek** [comment]
blocker #9

**Comment by farshidtorkaman** [comment]
I found the answer about that issue.

https://github.com/IdentityServer/IdentityServer4/issues/1758#issuecomment-426842106
